/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongltonline;

import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Admin
 */
public class CLIENT_EXAM extends javax.swing.JFrame {

    /**
     * Creates new form CLIENT_EXAM
     *
     */
    private static String examCode = "";
    int current = -1;
    int cauHienTai = -1;
    int dem = 0;
    int soCau = 0;

    String ansClient = "";
    String ans = "";
    String strKQ;

    ArrayList<String> cauChon = new ArrayList<>();
    ArrayList<String> ketQua = new ArrayList<>();
    ArrayList<Question> listQuestion = new ArrayList<>();

    public CLIENT_EXAM() {

    }

    public CLIENT_EXAM(String examCode) {
        initComponents();
        this.setTitle("PTIT PRACTICE");
        this.setLocation(500, 100);
        setExtendedState(CLIENT_EXAM.MAXIMIZED_BOTH);
        getQuestionFromServer("localhost", 13334, examCode);
        getNextQuestion();
        
        jlExamCode.setText("Exam Code: " + examCode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jrbB = new javax.swing.JRadioButton();
        jrbC = new javax.swing.JRadioButton();
        jrbA = new javax.swing.JRadioButton();
        jrbD = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpQuestion = new javax.swing.JTextPane();
        jlExamCode = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PTIT PRACTICE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("PTIT PRACTICE");

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jtpQuestion);

        jlExamCode.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jrbD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jlExamCode, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jlExamCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jrbA, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jrbB, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jrbC, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jrbD, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        if(jrbA.isSelected()){
            System.out.println("A");
            cauChon.add("A");
            jrbA.setSelected(false);
        }
        if(jrbB.isSelected()){
            System.out.println("B");
            cauChon.add("B");
            jrbB.setSelected(false);
        }
        if(jrbC.isSelected()){
            System.out.println("C");
            cauChon.add("C");
            jrbC.setSelected(false);
        }
        if(jrbD.isSelected()){
            System.out.println("D");
            cauChon.add("D");
            jrbD.setSelected(false);
        }
        getNextQuestion();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        correctAnswer();
        JOptionPane.showOptionDialog(null, "Are u sure to submit?", "Yes", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        this.setVisible(false);
        CLIENT_RESULT clientRes = new CLIENT_RESULT();
        clientRes.setVisible(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLIENT_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLIENT_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLIENT_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLIENT_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLIENT_EXAM(examCode).setVisible(true);
            }
        });
    }

    public void getQuestionFromServer(String address, int port, String examCode) {
        try {
            Socket client = new Socket(address, port);

            DataOutputStream dos = new DataOutputStream(client.getOutputStream());
            dos.writeUTF(examCode);

            ObjectInputStream ois = new ObjectInputStream(client.getInputStream());
            ArrayList<String> listq_c = new ArrayList<>();

            Question CH = new Question();

            try {
                listq_c = (ArrayList<String>) ois.readObject();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }

            int dem = 0;
            for (int i = 0; i < listq_c.size(); i++) {
                if (dem < 4) {
                    CH = new Question();

                    CH.setQuestion(Integer.parseInt(listq_c.get(i)));
                    CH.setNoiDung(listq_c.get(i + 1));
                    CH.setCauA(listq_c.get(i + 2));
                    CH.setCauB(listq_c.get(i + 3));
                    CH.setCauC(listq_c.get(i + 4));
                    CH.setCauD(listq_c.get(i + 5));
                    CH.setAnswer(listq_c.get(i + 6));

                    listQuestion.add(CH);
                    i = i + 6;
                }
                dem++;
            }
            dem = 0;
            ansClient = "";
            soCau = listQuestion.size();
            dem++;

            dos.close();
            ois.close();
            client.close();

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void getNextQuestion() {
        current++;
//
//        if (current > 0) {
//            if (jrbA.isSelected()) {
//                cauChon.add("A");
//                ansClient += dem + "///";
//                ansClient += ans + "///";
//                System.out.println("A");
//            }
//
//            if (jrbB.isSelected()) {
//                cauChon.add("B");
//                ansClient += dem + "///";
//                ansClient += ans + "///";
//                System.out.println("B");
//            }
//
//            if (jrbC.isSelected()) {
//                cauChon.add("C");
//                ansClient += dem + "///";
//                ansClient += ans + "///";
//                System.out.println("C");
//            }
//
//            if (jrbD.isSelected()) {
//                cauChon.add("D");
//                ansClient += dem + "///";
//                ansClient += ans + "///";
//                System.out.println("D");
//            }
//        }
        if (current < soCau) {
            dem++;
            Question ques = listQuestion.get(current);
            jtpQuestion.setText(dem + ": " + ques.getNoiDung());
            jrbA.setText("A. " + ques.getCauA());
            jrbB.setText("B. " + ques.getCauB());
            jrbC.setText("C. " + ques.getCauC());
            jrbD.setText("D. " + ques.getCauD());
        }
        else{
            btnNext.setEnabled(false);
        }
    }

    public void correctAnswer() {
        int cau = 0;
        int dem = 0;
        for (int i = 0; i < soCau; i++) {
            dem++;

            String answer = listQuestion.get(i).getAnswer();
            answer = answer.replace(" ", "");
            String chon = cauChon.get(i);
            
            

            strKQ = dem + "Correct Answer -- Your answer: " + answer + "--" + chon;
            
            System.out.println(strKQ);
//            ketQua.add(strKQ);
            if (chon.equals(answer)) {
                System.out.println("Correct");
                cau++;  
            } else {
                System.out.println("INCORRECT");
            }
        }

        Answer.score = cau;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlExamCode;
    private javax.swing.JRadioButton jrbA;
    private javax.swing.JRadioButton jrbB;
    private javax.swing.JRadioButton jrbC;
    private javax.swing.JRadioButton jrbD;
    private javax.swing.JTextPane jtpQuestion;
    // End of variables declaration//GEN-END:variables
}
